### ISSUE TITLE
Please parse style cls attributes in header !!!

### ISSUE THREAD

**Issue by sroik** [onmyway133/Snowflake#11]
<img width="1680" alt="screen shot 2018-02-11 at 10 01 37 am" src="https://user-images.githubusercontent.com/7701363/36070744-91cf55d4-0f12-11e8-832b-03c6520bb912.png">

**Comment by onmyway133** [comment]
@sroik Hi, this is nice to have. I'm a bit busy nowadays so I'm not sure if I can make it now. If you come up with PR I'm glad to review it
