### ISSUE TITLE
Playground not working

### ISSUE THREAD

**Issue by DanielAsher** [onmyway133/Snowflake#12]
Hi - this looks like a great project!

I ran into a problem when starting up the iOS playground and was wondering if you had a clue as to want was going wrong. 

Thanks,

Daniel
```
git clone https://github.com/onmyway133/Snowflake
cd Snowflake
carthage bootstrap --platform ios --cache-builds
xcodebuild -project Snowflake.xcodeproj -target Snowflake-iOS
open -a Xcode Snowflake.xcodeproj
```
Navigate to `Playground-iOS.playground`
```
Playground execution failed:

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Reindeers-libxml2.h"
        ^

/Users/danielasher/Downloads/Snowflake-master/Carthage/Checkouts/Reindeers/Cocoapods/Reindeers-libxml2.h:1:9: note: in file included from /Users/danielasher/Downloads/Snowflake-master/Carthage/Checkouts/Reindeers/Cocoapods/Reindeers-libxml2.h:1:
#import <libxml2/libxml/HTMLparser.h>
        ^

error: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^

error: could not build Objective-C module 'Clibxml2'

```

**Comment by DanielAsher** [comment]
Dead as a doornail.

**Comment by onmyway133** [comment]
@DanielAsher Hi, sorry for late response. I think Playground is having hard time finding the `libxml2` library used in `Reindeers`. I haven't managed to fix it, but in the mean time you can try playing with Snowflake via the example project https://github.com/onmyway133/Snowflake/tree/master/Example/SnowflakeDemo ❤️

**Comment by DanielAsher** [comment]
Hi @onmyway133,
this is a common problem with the libraries that use C (see [SWXMLHash](https://github.com/drmohundro/SWXMLHash) as another example). This seems to be because the `module.modulemap` is not fully correct and public `headers` are missing. I think you need to add more of the `libxml2` headers. Can I recommend you use or take a look at [Ji](https://github.com/honghaoz/Ji), which is an excellent framework also based on `libxml2` and works beautifully in a playground. I think you can solve this problem!
best wishes,
Daniel

P.S. Feel free to close again with a won't fix label 👍. Everybody's so very busy!
