### ISSUE TITLE
Please push podspec 2.0.0 to CocoaPods

### ISSUE THREAD

**Issue by sroik** [onmyway133/Snowflake#13]

**Comment by onmyway133** [comment]
@sroik Hi, the name `Snowflake` https://cocoapods.org/?q=snowflake has already been taken, so I can't push this to CocoaPods. But you can still point directly to this repo ❤️

**Comment by sroik** [comment]
But you can use different podspec and module names.
Like:

```ruby
Pod::Spec.new do |s|
  s.name = 'SnowflakeSVG'
  s.module_name = 'Snowflake'
***
```

**Comment by onmyway133** [comment]
@sroik Hi, I just made it `FantasticSnowflake`, which has version `2.2.0`. Can you check to see if it works for you?

**Comment by sroik** [comment]
Hi @onmyway133. Cool. It is 👍
Thanks a lot ))

**Comment by onmyway133** [comment]
@sroik Glad that you find this useful ❤️
