### ISSUE TITLE
Can't actually install or build

### ISSUE THREAD

**Issue by alexbartisro** [onmyway133/Snowflake#14]
Sample project doesn't even work.

If I add
```
pod 'Snowflake', git: 'https://github.com/onmyway133/Snowflake'
```
to my Podfile, it fails to install
Pre-downloading: `Snowflake` from `https://github.com/onmyway133/Snowflake`
[!] Unable to find a specification for 'Snowflake'.

If I add FantasticSnowflake, it installs but can't find the module.

**Comment by onmyway133** [comment]
@trusk89 Hi, as stated in the README, you need to use `FantasticSnowflake` because the name `Snowflake` was taken by another person on CocoaPods. Can you try with CocoaPods 1.4.0 ?

**Comment by alexbartisro** [comment]
Yes, it says one or the other, so I tried both.

But I did get it to work with ```FantasticSnowflake``` but when rendering an svg in entered in somewhat of a loop and started eating ram, so I killed it when it got to 1.5GBs and switched to another framework.

Thanks for the help though!

**Comment by onmyway133** [comment]
@trusk89 Hi can I somehow see that svg so I can debug it?
