### ISSUE TITLE
Carthage requires tagged version

### ISSUE THREAD

**Issue by nverinaud** [onmyway133/Snowflake#2]
Running `carthage update` provokes an error 😞:

```
*** Cloning Snowflake
No tagged versions found for github "onmyway133/Snowflake"
```

Could you tag the repo with a version like 0.1.0 ?

**Comment by onmyway133** [comment]
@nverinaud Hi, can you point to master for now, like

```
github "onmyway133/Snowflake" "master"
```

**Comment by onmyway133** [comment]
@nverinaud Hi, the tag is https://github.com/onmyway133/Snowflake/releases/tag/1.0. You can check 😇
