### ISSUE TITLE
Minimum Deployment Target for Reindeers is set to 9

### ISSUE THREAD

**Issue by olita1986** [onmyway133/Snowflake#7]
While pod installing snowflake, I run into this error message:

[!] Unable to satisfy the following requirements:

- `Reindeers` required by `Snowflake (2.0.0)`

Specs satisfying the `Reindeers` dependency were found, but they required a higher minimum deployment target.

My current project is set to 8, so that might be the problem

**Comment by onmyway133** [comment]
@olita1986 Hi, I've just released https://github.com/onmyway133/Reindeers/releases/tag/1.3.0 which supports iOS 8.0. Sorry for the confusion. You can just `pod repo update` and `pod update Snowflake` again to see the changes.

**Comment by olita1986** [comment]
@onmyway133 it built great! I will give it a try. Thank you very for the fast responses and help! you are the best!

**Comment by onmyway133** [comment]
@olita1986 Nice. I will close this issue for now. Feel free to reopen it if you have any issue 👍
