### ISSUE TITLE
Can I manually drag this and use it in my Objective C project ?

### ISSUE THREAD

**Issue by sriteja25** [onmyway133/Snowflake#9]
I want use this framework for my project which I written in Objective C, for some reasons I cannot add it using Cocoapods as still some of libraries used are static , so I cannot use_framework in my pods file.

Which files so as to use this framework in my Project ?

**Comment by onmyway133** [comment]
@sriteja25 Hi, you can try adding source files in https://github.com/onmyway133/Snowflake/tree/master/Sources/iOS and also in https://github.com/onmyway133/Reindeers/tree/master/Sources

I haven't checked with ObjC project, but if you have any further questions, just ping me

**Comment by sriteja25** [comment]
I tried this, was getting error, No such module Reindeers exists in import Reindeers in Paths.swift.

**Comment by onmyway133** [comment]
@sriteja25 Reindeers is based on libxml2 https://github.com/onmyway133/Reindeers/blob/master/Reindeers.podspec#L23

So in your project, you need to declare correct library search path and header search path
